### ISSUE TITLE
Unexpected end of JSON input error

### ISSUE THREAD

**Issue by AlcuZan** [fberrizbeitia/RSS-API#1] opened 2017-01-19 18:10 UTC
This is my HTML File:
```
<html>
  <head>
	<script src="https://code.jquery.com/jquery-1.11.3.js"   integrity="sha256-IGWuzKD7mwVnNY01LtXxq3L84Tm/RJtNCYBfXZw3Je0="   crossorigin="anonymous"></script>
	<script src="lib/feed.js"></script>
<style>
#feed {font-size:13px; font-family:Arial; line-height:18px; margin:0; padding:0;}
#feed {color:#000; text-decoration:none;}
#feed a {color:#BE1E3C; text-align: right;}
</style>
  </head>
  <body>
    <div id="feed"></div><br>
	<script type="text/javascript" src= "script_rssapi.js"> 
	</script> 
  </body>
</html>
```

This is my script_rssapi.js code:
```
var objRss = new rss();
		var feedURL = "https://www.tu-braunschweig.de/marketing/aktuellesundtermine/aktuell/rssfeed.xml";
		var count = 7;
		objRss.displayAsinc(feedURL, "feed", 'pubDate','date','desc',count, 512);
```
If I try to run it, I get:
```
Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at setItems (feed.js:161)
    at Object.success (feed.js:244)
    at fire (jquery-1.11.3.js:3148)
    at Object.fireWith [as resolveWith] (jquery-1.11.3.js:3260)
    at done (jquery-1.11.3.js:9314)
    at XMLHttpRequest.callback (jquery-1.11.3.js:9718)
```
Am I doing something wrong?

**Comment by fberrizbeitia** [comment] 2017-01-19 18:32
What your doing looks ok to me, both your code and rss document ... I think it might have something to do with the configuration. 

The feed url is https ... are calling from a secure connection too ? Does it work on the test page ? can you try with http instead a see if it's works ?

Can you post or send me by email your service/config.php file and lib/feed.js ? 

Regards

**Comment by AlcuZan** [comment] 2017-01-19 21:56
Thank you for the quick response.
Yes, it's calling from a secure location. 
Otherwise I think I'd get a Mixed Content Error, right? That's why I can't try it with HTTP, i get that error then. What do you mean by test page? I can't test it locally, can I?
Sure, config File looks like this:
```
$ALLOWED_DOMAINS = array('https://www.tu-braunschweig.de/marketing', 'https://redaktionssystem.tu-braunschweig.de/');
$BASE_FEED_URL = 'https://marketing.rz.tu-bs.de/marketing/test/cache/feeds';
```
And feed.js looks like this (I won't post the whole things, only the important part):
```
var serviceURL = 'https://marketing.rz.tu-bs.de/marketing/test/service/RSSget.php';
var loaderURL = 'https://marketing.rz.tu-bs.de/marketing/test/lib/loading_50.gif';
```
The files are all where they are supposed to be.

**Comment by photomedia** [comment] 2017-01-19 22:38
This is the test page: https://github.com/fberrizbeitia/RSS-API/blob/master/test.php

**Comment by AlcuZan** [comment] 2017-01-20 11:38
Ah, didn't see that one. If i paste the link in there and press try, absolutely nothing happens. Then I go into the console and I get the same "unexpected end of JSON" error. I tried a different feed and still get the same error.

**Comment by t-aras** [comment] 2017-01-20 14:08
I get the same error and it happens at 
```
setItem @ feed.js:161
success @ feed.je:244
```

What could it be?

**Comment by fberrizbeitia** [comment] 2017-01-20 15:10
I think the problem is in the config.php file ... You don't need to specify the whole path:

`https://www.tu-braunschweig.de/marketing` 
just  
`https://www.tu-braunschweig.de `

In you case I would also remove the "/" at the end. That may cause issues too. 
Another thing I would do is include the www and non www variation of the domain, just to be safe.

I hope this help.

**Comment by fberrizbeitia** [comment] 2017-01-20 15:13
@breeaakdancc  can you provide more info on your issue. I might very well be also a problem in the configuration.

Can you post or send me by email your service/config.php file and lib/feed.js ?

**Comment by fberrizbeitia** [comment] 2017-01-20 15:15
@AlcuZan  I forgot something. To have the test page working you'll to add this domain to the white list:

`https://marketing.rz.tu-bs.de`

**Comment by AlcuZan** [comment] 2017-01-20 15:26
Now I get `Failed to load resource: the server responded with a status of 500 (Internal Server Error)` regarding https://marketing.rz.tu-bs.de/marketing/test/service/RSSget.php (the file is there, double checked)

**Comment by fberrizbeitia** [comment] 2017-01-20 15:40
Seems a php coding error. Can you "un-comment" line 243 in /lib/feed.js

`console.log(data)` 

We may get some more info there

**Comment by t-aras** [comment] 2017-01-20 15:41
@fberrizbeitia 
my config.php:
`<?php
$ALLOWED_DOMAINS = array('http://localhost', 'https://localhost');
$BASE_FEED_URL = 'http://localhost/cache/feeds/';
?>
`

and my feed.js:
http://pastebin.com/pe9Xs1YB

**Comment by fberrizbeitia** [comment] 2017-01-20 15:48
@breeaakdancc ... Can you try removing the https from one of the alloweed domains. 
Also check on chrome -> developer tools -> nerwork -> XHR click on the RSSget.php look for the request header. In the header look for the Referer . The domain of the Referer  URL must be included in allowed doimain for the api to work.

**Comment by t-aras** [comment] 2017-01-20 15:52
@fberrizbeitia 
Thanks. The Referer is localhost
But now I get also 
`500 (Internal Server Error)`

And 
`PHP Warning:  file_get_contents(index.xml): failed to open stream: No such file or directory in /var/www/html/service/feedIndex.php on line 10, referer: http://localhost/test.php
`

**Comment by fberrizbeitia** [comment] 2017-01-20 16:03
Hi @breeaakdancc 

You need to to specify a full URL in the input box if your using the test page or on the displayAsinc function call. Something like: 

`http://localhost/your-path/feed-name.xml `

If you look at the warning is trying to access a file on the same directory not a URL on the web.

Cheers

**Comment by AlcuZan** [comment] 2017-01-20 16:09
@fberrizbeitia Uncommenting the console.log(data) in line 243 doesn't do anything! I tried alert(data) and also nothing happens there. breeaakdncc gets it also (the Internal Server Error), seems to be a problem in RSSget.php here.

**Comment by fberrizbeitia** [comment] 2017-01-20 16:21
@AlcuZan  ... The CORS part is working. You can see the in the response header 
`Access-Control-Allow-Origin:https://marketing.rz.tu-bs.de`

I think the error may be in the caching. Maybe folders permissions ? can you look at the log files, in cache/logs/requests ? Can you check inthe cache/feeds/ folder in some files were created?

**Comment by AlcuZan** [comment] 2017-01-20 16:24
requests.log is empty. cache/feeds only has the feed.xml from your package, which is also empty.

**Comment by fberrizbeitia** [comment] 2017-01-20 16:42
Can you check the permissions. Both the cache (and subfolders) and the service folders must have writing permissions. I think this may be the cause.

**Comment by AlcuZan** [comment] 2017-01-20 17:00
I have no idea how to do this

**Comment by AlcuZan** [comment] 2017-01-20 17:05
Not sure if I did it right. I right clicked on the folders  -> properties -> permissions -> checked every box 
Doesn't do any good though
Edit: Got something now! cache/feeds has a new file `70710f834af292a80de6703ffc4bbe5e.xml` that has the following lines:

```
<?xml version="1.0" encoding="utf-8"?>
<rss xmlns:atom="http://www.w3.org/2005/Atom" version="2.0"><channel><title></title><description></description><link>../cache/feeds/70710f834af292a80de6703ffc4bbe5e.xml</link><pubDate>Fri, 20 Jan 2017 18:01:39 +0100</pubDate><language>en-us</language><item><title>WiMi gesucht (100% E-13 TV-L)</title><description></description><link><![CDATA[http://www.tu-braunschweig.de/marketing/aktuellesundtermine/aktuell#2017-01-19]]></link><guid><![CDATA[2017-01-19]]></guid><pubDate>19 Jan 2017 14:43:00 GMT</pubDate></item><item><title>Gastvortrag Dr. Martin Kassubek</title><description></description><link><![CDATA[http://www.tu-braunschweig.de/marketing/aktuellesundtermine/aktuell#2017-01-11]]></link><guid><![CDATA[2017-01-11]]></guid><pubDate>11 Jan 2017 14:49:00 GMT</pubDate></item><item><title>Verleihung fme-Preis</title><description></description><link><![CDATA[http://www.tu-braunschweig.de/marketing/aktuellesundtermine/aktuell#2016-11-29]]></link><guid><![CDATA[2016-11-29]]></guid><pubDate>29 Nov 2016 10:15:00 GMT</pubDate></item><item><title>Ehrendoktorwürde für Prof. Fritz</title><description></description><link><![CDATA[http://www.tu-braunschweig.de/marketing/aktuellesundtermine/aktuell#2016-11-21]]></link><guid><![CDATA[2016-11-21]]></guid><pubDate>21 Nov 2016 11:24:00 GMT</pubDate></item><item><title>Prüfungstermine im WS1617</title><description></description><link><![CDATA[http://www.tu-braunschweig.de/marketing/aktuellesundtermine/aktuell#2016-09-06]]></link><guid><![CDATA[2016-09-06]]></guid><pubDate>06 Sep 2016 14:32:00 GMT</pubDate></item><item><title>Lehrveranstaltungen im WS16/17</title><description></description><link><![CDATA[http://www.tu-braunschweig.de/marketing/aktuellesundtermine/aktuell#2016-08-24]]></link><guid><![CDATA[2016-08-24]]></guid><pubDate>24 Aug 2016 11:30:00 GMT</pubDate></item><item><title>Käuferverhalten und Marketing-Forschung WS16/17</title><description></description><link><![CDATA[http://www.tu-braunschweig.de/marketing/aktuellesundtermine/aktuell#2016-08-05]]></link><guid><![CDATA[2016-08-05]]></guid><pubDate>04 Aug 2016 22:00:00 GMT</pubDate></item></channel></rss>
```
Not sure how that helps me though. I still get the Internal Server Error and requests.log is still empty.

**Comment by fberrizbeitia** [comment] 2017-01-20 18:32
Are on windows ?. If so you can do this:

1. Right-click the directory, then choose Properties
2. Go to the Security tab
3. Find the IUSR account  (If IUSR is not in the list, add it by clicking Edit, then clicking Add, and then typing "IUSR" in the "Enter the object names to select" field.)
4. Highlight the user in the list, click Edit, and grant the account Modify and Write permissions

For screen shots refer to this page:
https://www.kbpublisher.com/kb/setting-up-folder-permissions-in-internet-information-services-(iis)_392.html

**Comment by AlcuZan** [comment] 2017-01-20 18:40
I use an FTP client to access the webspace, WinSCP.

**Comment by photomedia** [comment] 2017-01-20 21:49
https://winscp.net/eng/docs/ui_permissions

If you have access to the PHP log on your server, it should tell you where an error was encountered.

**Comment by AlcuZan** [comment] 2017-01-21 12:00
I found the issue. I added one line of code in RSSget.php:
`date_default_timezone_set ('Europe/Berlin');`
This resulted in the Internal Server Error being gone! I finally got it, I can see my feed! 
One more thing though: The pubDate entry for all items is empty - only in JSON though, the XML file has them! I found the source of this issue aswell! 
In feed.js one small typo in setItems - you wrote pubdate instead of pubDate! Changed it to pubDate and it works! I am so happy right now :D

**Comment by t-aras** [comment] 2017-01-23 08:04
@fberrizbeitia sorry for the late reply. 
I did use a full url: "https://www.heise.de/newsticker/heise-atom.xml"
what do I need to use as BASE_FEED_URL in my case? is BASE_FEED_URL='https://localhost/cache/feeds/'
is this right?

**Comment by t-aras** [comment] 2017-01-23 10:55
@fberrizbeitia  I solved the problem. It was because php5-curl and php5-xsl was not installed.

Thank you for this great API :)

**Comment by fberrizbeitia** [comment] 2017-01-23 14:21
Thanks @AlcuZan for pointing out the typo, I will correct and update the repo.
@breeaakdancc  I'm glad you solved the problem. Will add the php confoguration to the documentation.

Will close the issue now

**Closed as completed** 2017-01-23 14:22 UTC
